---
name: "Masquerade NAT Setup"
description: >
  Enables IP forwarding and configures NAT MASQUERADE
  for Home Assistant.
version: "1.0.0"
slug: "masqaddon"
init: false
startup: services
boot: auto
watchdog: false
host_network: true
privileged:
  - NET_ADMIN
image: "local/masqaddon"

stage: stable
url: "https://github.com/dimanyci/homeassistant-addons"
arch:
  - amd64
  - i386
  - aarch64
  - armv7
  - armhf

options:
  log_level: "info"
  commands: []

schema:
  log_level: str?
  commands:
    - str
